name: Python Package Workflow

env:
  LC_ALL: "en_US.UTF-8"
  LC_CTYPE: "en_US.UTF-8"

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'src/**'
      - 'test/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - main

jobs:
  pre-merge-check:
    name: Pre-Merge Check (Build & Test)
    runs-on: ubuntu-latest
    container:
      image: andreiolar1/python-poetry-mkdocs:3.12.7
    if: startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'refactor/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checks and tests
        run: make test
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: pypi
    container:
      image: andreiolar1/python-poetry-mkdocs:3.12.7
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the package
        run: make build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish
